apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathogene-app
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: pathogene-app
  template:
    metadata:
      labels:
        app: pathogene-app
    spec:
      containers:
        - name: pathogene-app
          image: mabouelkhir/pathogene11:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pathogene-app-service
spec:
  selector:
    app: pathogene-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
